// Image constants pointing to public/assets
const images = {
  about01: '/assets/about01.png',
  about02: '/assets/about02.png',
  about03: '/assets/about03.png',
  about04: '/assets/about04.png',
  adidas: '/assets/adidas.png',
  amazon: '/assets/amazon.png',
  api: '/assets/api.png',
  asus: '/assets/asus.png',
  bolt: '/assets/bolt.png',
  circle: '/assets/circle.svg',
  cpp: '/assets/cpp.png',
  css: '/assets/css.png',
  email: '/assets/email.png',
  figma: '/assets/figma.png',
  flutter: '/assets/flutter.png',
  git: '/assets/git.png',
  graphql: '/assets/graphql.png',
  html: '/assets/html.png',
  javascript: '/assets/javascript.png',
  logo: '/assets/logo.png',
  logo1: '/assets/result.png',
  logo2: '/assets/result (1).png',
  mobile: '/assets/mobile.png',
  mu5: '/assets/mu5.png',
  nb: '/assets/nb.png',
  node: '/assets/node.png',
  profile: '/assets/profile.png',
  python: '/assets/python.png',
  react: '/assets/react.png',
  redux: '/assets/redux.png',
  sass: '/assets/sass.png',
  skype: '/assets/skype.png',
  spotify: '/assets/spotify.png',
  typescript: '/assets/typescript.png',
  vue: '/assets/vue.png',
  Profile: '/assets/Hemant_Gehlod-removebg-preview.png',
  headerImg: '/assets/Hemant_Gehlod-removebg-preview.png',
};

export { images };
export default images;

