import projectsImg from './projectsImg';

const works = [
  {
    title: 'HireLyx',
    description: 'AI-powered recruitment platform that streamlines hiring with intelligent candidate matching, automated screening, and real-time collaboration for HR teams.',
    projectLink: 'https://hirelyx.com',
    codeLink: 'https://github.com/Hmtgit7/hirelyx',
    imgUrl: '/assets/projects/hirelyx.png',
    tags: ['Next JS', 'AI/ML'],
    featured: true,
    slug: 'hirelyx',
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'OpenAI', 'Redis', 'Docker'],
    category: 'SaaS Platform',
  },
  {
    title: 'Prajna',
    description: 'An intelligent learning management system with adaptive curriculum, real-time progress tracking, and AI-driven personalized study paths for students and educators.',
    projectLink: 'https://prajna.vercel.app',
    codeLink: 'https://github.com/Hmtgit7/prajna',
    imgUrl: '/assets/projects/prajna.png',
    tags: ['Next JS', 'AI/ML'],
    featured: true,
    slug: 'prajna',
    techStack: ['Next.js', 'TypeScript', 'MongoDB', 'Express', 'OpenAI', 'Socket.io', 'AWS'],
    category: 'EdTech Platform',
  },
  {
    title: 'Tagmaster',
    description: 'Tagmaster is a platform for creating and managing tags for your projects',
    projectLink: 'https://tagmaster.shopyfi.in',
    codeLink: 'https://github.com/shopy-fi',
    imgUrl: projectsImg.tagmaster,
    tags: ['Shopify App'],
    featured: false,
    slug: null,
  },
  {
    title: 'SyncSphere',
    description: 'SyncSphere is a shopify app that allows you to synchronize multiple stores inventory',
    projectLink: 'https://syncspher.shopyfi.in',
    codeLink: 'https://github.com/shopy-fi',
    imgUrl: projectsImg.syncsphere,
    tags: ['Shopify App'],
    featured: false,
    slug: null,
  },
  {
    title: 'Threads Clone',
    description: 'Threads Clone is a social media platform that allows you to share your thoughts and ideas with the world',
    projectLink: 'https://threads-clone-two-omega.vercel.app/',
    codeLink: 'https://github.com/Hmtgit7/threads-clone',
    imgUrl: projectsImg.threadsClone,
    tags: ['MERN'],
    featured: false,
    slug: null,
  },
  {
    title: 'Realtime Spotify Clone',
    description: 'Realtime Spotify Clone is a music streaming platform that allows you to listen to your favorite songs with your friends',
    projectLink: 'https://realtime-spotify-clone-ruddy.vercel.app/',
    codeLink: 'https://github.com/Hmtgit7/realtime-spotify-clone',
    imgUrl: projectsImg.realtimeSpotify,
    tags: ['MERN'],
    featured: false,
    slug: null,
  },
  {
    title: 'Shopyfi',
    description: 'Shopyfi is a platform to explore shopify apps to boost your store',
    projectLink: 'https://shopyfi.in',
    codeLink: 'https://github.com/shopy-fi/shopyfi',
    imgUrl: projectsImg.shopyfi,
    tags: ['MERN'],
    featured: false,
    slug: null,
  },
  {
    title: 'AI Career Coach',
    description: 'AI Career Coach is a platform that allows you to get career advice from AI',
    projectLink: 'https://ai-career-coach-navy.vercel.app',
    codeLink: 'https://github.com/Hmtgit7/ai-career-coach',
    imgUrl: projectsImg.aiCareerCoach,
    tags: ['Next JS'],
    featured: false,
    slug: null,
  },
  {
    title: 'Health Tracker',
    description: 'Health Tracker is a platform that allows you to track your health',
    projectLink: 'https://health-tracker-six-beige.vercel.app/',
    codeLink: 'https://github.com/Hmtgit7/health-tracker',
    imgUrl: projectsImg.healthTracker,
    tags: ['Next JS'],
    featured: false,
    slug: null,
  },
  {
    title: 'Employee Management System',
    description: 'Employee Management System is a platform that allows you to manage your employees',
    projectLink: 'https://employee-management-steel-phi.vercel.app/',
    codeLink: 'https://github.com/Hmtgit7/employee-management-system',
    imgUrl: projectsImg.employeeManagement,
    tags: ['Python'],
    featured: false,
    slug: null,
  },
  {
    title: 'Bitly Clone',
    description: 'Bitly Clone is a platform that allows you to shorten your links',
    projectLink: 'https://bitly-clone-shopyfi.vercel.app/',
    codeLink: 'https://github.com/Hmtgit7/bitly-clone',
    imgUrl: projectsImg.bitly,
    tags: ['Java'],
    featured: false,
    slug: null,
  },
  {
    title: 'Movie Flixer',
    description: 'Movie Flixer is a platform that allows you to watch movies online',
    projectLink: 'https://movie-flixer.netlify.app/',
    codeLink: 'https://github.com/Hmtgit7/movieflixer',
    imgUrl: projectsImg.movieFlixer,
    tags: ['React JS'],
    featured: false,
    slug: null,
  },
  {
    title: 'HomeNavPro: A Ecommerce Template',
    description: 'Ecommerce React App Template',
    projectLink: 'https://homenav-pro.netlify.app/',
    codeLink: 'https://github.com/Hmtgit7/HomeNav-PRO',
    imgUrl: projectsImg.homeNavPro,
    tags: ['React JS'],
    featured: false,
    slug: null,
  },
  {
    title: 'Spotify Clone',
    description: 'Spotify Clone Using React JS And Spotify API And SDK',
    projectLink: 'https://mymusicapp-phi.vercel.app/',
    codeLink: 'https://github.com/Hmtgit7/mymusicapp',
    imgUrl: projectsImg.spotify,
    tags: ['React JS'],
    featured: false,
    slug: null,
  },
  {
    title: 'Smart Bookmark Manager',
    description: 'A smart bookmark manager built with React JS',
    projectLink: 'https://smart-bookmark-app-lilac-phi.vercel.app',
    codeLink: 'https://github.com/Hmtgit7/smart-bookmark-app',
    imgUrl: projectsImg.bookmarkManager,
    tags: ['React JS'],
    featured: false,
    slug: null,
  },
];

export default works;
